# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['CloudinitDiskArgs', 'CloudinitDisk']

@pulumi.input_type
class CloudinitDiskArgs:
    def __init__(__self__, *,
                 meta_data: pulumi.Input[_builtins.str],
                 user_data: pulumi.Input[_builtins.str],
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 network_config: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a CloudinitDisk resource.
        :param pulumi.Input[_builtins.str] meta_data: Cloud-init meta-data content (usually YAML)
        :param pulumi.Input[_builtins.str] user_data: Cloud-init user-data content (usually YAML)
        :param pulumi.Input[_builtins.str] name: Name for this cloud-init disk resource
        :param pulumi.Input[_builtins.str] network_config: Cloud-init network configuration (optional, usually YAML)
        """
        pulumi.set(__self__, "meta_data", meta_data)
        pulumi.set(__self__, "user_data", user_data)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if network_config is not None:
            pulumi.set(__self__, "network_config", network_config)

    @_builtins.property
    @pulumi.getter(name="metaData")
    def meta_data(self) -> pulumi.Input[_builtins.str]:
        """
        Cloud-init meta-data content (usually YAML)
        """
        return pulumi.get(self, "meta_data")

    @meta_data.setter
    def meta_data(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "meta_data", value)

    @_builtins.property
    @pulumi.getter(name="userData")
    def user_data(self) -> pulumi.Input[_builtins.str]:
        """
        Cloud-init user-data content (usually YAML)
        """
        return pulumi.get(self, "user_data")

    @user_data.setter
    def user_data(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "user_data", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name for this cloud-init disk resource
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="networkConfig")
    def network_config(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cloud-init network configuration (optional, usually YAML)
        """
        return pulumi.get(self, "network_config")

    @network_config.setter
    def network_config(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "network_config", value)


@pulumi.input_type
class _CloudinitDiskState:
    def __init__(__self__, *,
                 meta_data: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 network_config: Optional[pulumi.Input[_builtins.str]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 size: Optional[pulumi.Input[_builtins.float]] = None,
                 user_data: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering CloudinitDisk resources.
        :param pulumi.Input[_builtins.str] meta_data: Cloud-init meta-data content (usually YAML)
        :param pulumi.Input[_builtins.str] name: Name for this cloud-init disk resource
        :param pulumi.Input[_builtins.str] network_config: Cloud-init network configuration (optional, usually YAML)
        :param pulumi.Input[_builtins.str] path: Full path to the generated ISO file
        :param pulumi.Input[_builtins.float] size: Size of the ISO file in bytes
        :param pulumi.Input[_builtins.str] user_data: Cloud-init user-data content (usually YAML)
        """
        if meta_data is not None:
            pulumi.set(__self__, "meta_data", meta_data)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if network_config is not None:
            pulumi.set(__self__, "network_config", network_config)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if size is not None:
            pulumi.set(__self__, "size", size)
        if user_data is not None:
            pulumi.set(__self__, "user_data", user_data)

    @_builtins.property
    @pulumi.getter(name="metaData")
    def meta_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cloud-init meta-data content (usually YAML)
        """
        return pulumi.get(self, "meta_data")

    @meta_data.setter
    def meta_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "meta_data", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name for this cloud-init disk resource
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="networkConfig")
    def network_config(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cloud-init network configuration (optional, usually YAML)
        """
        return pulumi.get(self, "network_config")

    @network_config.setter
    def network_config(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "network_config", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Full path to the generated ISO file
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def size(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Size of the ISO file in bytes
        """
        return pulumi.get(self, "size")

    @size.setter
    def size(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "size", value)

    @_builtins.property
    @pulumi.getter(name="userData")
    def user_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cloud-init user-data content (usually YAML)
        """
        return pulumi.get(self, "user_data")

    @user_data.setter
    def user_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_data", value)


@pulumi.type_token("libvirt:index/cloudinitDisk:CloudinitDisk")
class CloudinitDisk(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 meta_data: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 network_config: Optional[pulumi.Input[_builtins.str]] = None,
                 user_data: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a CloudinitDisk resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] meta_data: Cloud-init meta-data content (usually YAML)
        :param pulumi.Input[_builtins.str] name: Name for this cloud-init disk resource
        :param pulumi.Input[_builtins.str] network_config: Cloud-init network configuration (optional, usually YAML)
        :param pulumi.Input[_builtins.str] user_data: Cloud-init user-data content (usually YAML)
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CloudinitDiskArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a CloudinitDisk resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CloudinitDiskArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CloudinitDiskArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 meta_data: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 network_config: Optional[pulumi.Input[_builtins.str]] = None,
                 user_data: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CloudinitDiskArgs.__new__(CloudinitDiskArgs)

            if meta_data is None and not opts.urn:
                raise TypeError("Missing required property 'meta_data'")
            __props__.__dict__["meta_data"] = meta_data
            __props__.__dict__["name"] = name
            __props__.__dict__["network_config"] = network_config
            if user_data is None and not opts.urn:
                raise TypeError("Missing required property 'user_data'")
            __props__.__dict__["user_data"] = user_data
            __props__.__dict__["path"] = None
            __props__.__dict__["size"] = None
        super(CloudinitDisk, __self__).__init__(
            'libvirt:index/cloudinitDisk:CloudinitDisk',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            meta_data: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            network_config: Optional[pulumi.Input[_builtins.str]] = None,
            path: Optional[pulumi.Input[_builtins.str]] = None,
            size: Optional[pulumi.Input[_builtins.float]] = None,
            user_data: Optional[pulumi.Input[_builtins.str]] = None) -> 'CloudinitDisk':
        """
        Get an existing CloudinitDisk resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] meta_data: Cloud-init meta-data content (usually YAML)
        :param pulumi.Input[_builtins.str] name: Name for this cloud-init disk resource
        :param pulumi.Input[_builtins.str] network_config: Cloud-init network configuration (optional, usually YAML)
        :param pulumi.Input[_builtins.str] path: Full path to the generated ISO file
        :param pulumi.Input[_builtins.float] size: Size of the ISO file in bytes
        :param pulumi.Input[_builtins.str] user_data: Cloud-init user-data content (usually YAML)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CloudinitDiskState.__new__(_CloudinitDiskState)

        __props__.__dict__["meta_data"] = meta_data
        __props__.__dict__["name"] = name
        __props__.__dict__["network_config"] = network_config
        __props__.__dict__["path"] = path
        __props__.__dict__["size"] = size
        __props__.__dict__["user_data"] = user_data
        return CloudinitDisk(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="metaData")
    def meta_data(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud-init meta-data content (usually YAML)
        """
        return pulumi.get(self, "meta_data")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name for this cloud-init disk resource
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="networkConfig")
    def network_config(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Cloud-init network configuration (optional, usually YAML)
        """
        return pulumi.get(self, "network_config")

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Output[_builtins.str]:
        """
        Full path to the generated ISO file
        """
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def size(self) -> pulumi.Output[_builtins.float]:
        """
        Size of the ISO file in bytes
        """
        return pulumi.get(self, "size")

    @_builtins.property
    @pulumi.getter(name="userData")
    def user_data(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud-init user-data content (usually YAML)
        """
        return pulumi.get(self, "user_data")

