# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetNodeDevicesResult',
    'AwaitableGetNodeDevicesResult',
    'get_node_devices',
    'get_node_devices_output',
]

@pulumi.output_type
class GetNodeDevicesResult:
    """
    A collection of values returned by getNodeDevices.
    """
    def __init__(__self__, capability=None, devices=None, id=None):
        if capability and not isinstance(capability, str):
            raise TypeError("Expected argument 'capability' to be a str")
        pulumi.set(__self__, "capability", capability)
        if devices and not isinstance(devices, list):
            raise TypeError("Expected argument 'devices' to be a list")
        pulumi.set(__self__, "devices", devices)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def capability(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "capability")

    @_builtins.property
    @pulumi.getter
    def devices(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "devices")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")


class AwaitableGetNodeDevicesResult(GetNodeDevicesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNodeDevicesResult(
            capability=self.capability,
            devices=self.devices,
            id=self.id)


def get_node_devices(capability: Optional[_builtins.str] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNodeDevicesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['capability'] = capability
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('libvirt:index/getNodeDevices:getNodeDevices', __args__, opts=opts, typ=GetNodeDevicesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetNodeDevicesResult(
        capability=pulumi.get(__ret__, 'capability'),
        devices=pulumi.get(__ret__, 'devices'),
        id=pulumi.get(__ret__, 'id'))
def get_node_devices_output(capability: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNodeDevicesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['capability'] = capability
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('libvirt:index/getNodeDevices:getNodeDevices', __args__, opts=opts, typ=GetNodeDevicesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetNodeDevicesResult(
        capability=pulumi.get(__response__, 'capability'),
        devices=pulumi.get(__response__, 'devices'),
        id=pulumi.get(__response__, 'id')))
