# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetDomainInterfaceAddressesResult',
    'AwaitableGetDomainInterfaceAddressesResult',
    'get_domain_interface_addresses',
    'get_domain_interface_addresses_output',
]

@pulumi.output_type
class GetDomainInterfaceAddressesResult:
    """
    A collection of values returned by getDomainInterfaceAddresses.
    """
    def __init__(__self__, domain=None, id=None, interfaces=None, source=None):
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if interfaces and not isinstance(interfaces, list):
            raise TypeError("Expected argument 'interfaces' to be a list")
        pulumi.set(__self__, "interfaces", interfaces)
        if source and not isinstance(source, str):
            raise TypeError("Expected argument 'source' to be a str")
        pulumi.set(__self__, "source", source)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> _builtins.str:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def interfaces(self) -> Sequence['outputs.GetDomainInterfaceAddressesInterfaceResult']:
        return pulumi.get(self, "interfaces")

    @_builtins.property
    @pulumi.getter
    def source(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "source")


class AwaitableGetDomainInterfaceAddressesResult(GetDomainInterfaceAddressesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDomainInterfaceAddressesResult(
            domain=self.domain,
            id=self.id,
            interfaces=self.interfaces,
            source=self.source)


def get_domain_interface_addresses(domain: Optional[_builtins.str] = None,
                                   source: Optional[_builtins.str] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDomainInterfaceAddressesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['source'] = source
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('libvirt:index/getDomainInterfaceAddresses:getDomainInterfaceAddresses', __args__, opts=opts, typ=GetDomainInterfaceAddressesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetDomainInterfaceAddressesResult(
        domain=pulumi.get(__ret__, 'domain'),
        id=pulumi.get(__ret__, 'id'),
        interfaces=pulumi.get(__ret__, 'interfaces'),
        source=pulumi.get(__ret__, 'source'))
def get_domain_interface_addresses_output(domain: Optional[pulumi.Input[_builtins.str]] = None,
                                          source: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDomainInterfaceAddressesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['source'] = source
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('libvirt:index/getDomainInterfaceAddresses:getDomainInterfaceAddresses', __args__, opts=opts, typ=GetDomainInterfaceAddressesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetDomainInterfaceAddressesResult(
        domain=pulumi.get(__response__, 'domain'),
        id=pulumi.get(__response__, 'id'),
        interfaces=pulumi.get(__response__, 'interfaces'),
        source=pulumi.get(__response__, 'source')))
