# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['NetworkArgs', 'Network']

@pulumi.input_type
class NetworkArgs:
    def __init__(__self__, *,
                 autostart: Optional[pulumi.Input[_builtins.bool]] = None,
                 bandwidth: Optional[pulumi.Input['NetworkBandwidthArgs']] = None,
                 bridge: Optional[pulumi.Input['NetworkBridgeArgs']] = None,
                 dns: Optional[pulumi.Input['NetworkDnsArgs']] = None,
                 domain: Optional[pulumi.Input['NetworkDomainArgs']] = None,
                 forward: Optional[pulumi.Input['NetworkForwardArgs']] = None,
                 ips: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]]] = None,
                 ipv6: Optional[pulumi.Input[_builtins.str]] = None,
                 mac: Optional[pulumi.Input['NetworkMacArgs']] = None,
                 metadata: Optional[pulumi.Input['NetworkMetadataArgs']] = None,
                 mtu: Optional[pulumi.Input['NetworkMtuArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port_groups: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]]] = None,
                 port_options: Optional[pulumi.Input['NetworkPortOptionsArgs']] = None,
                 routes: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]]] = None,
                 trust_guest_rx_filters: Optional[pulumi.Input[_builtins.str]] = None,
                 virtual_port: Optional[pulumi.Input['NetworkVirtualPortArgs']] = None,
                 vlan: Optional[pulumi.Input['NetworkVlanArgs']] = None):
        """
        The set of arguments for constructing a Network resource.
        :param pulumi.Input[_builtins.bool] autostart: Whether the network should be started automatically when the host boots
        :param pulumi.Input['NetworkBandwidthArgs'] bandwidth: Configures overall QoS bandwidth limits for the virtual network, enabling nested inbound/outbound rate settings when present.
        :param pulumi.Input['NetworkDnsArgs'] dns: Enables configuration of DNS services for the virtual network, including forwarders and static records. Presence of this block turns on DNS handling according to its child settings.
        :param pulumi.Input['NetworkDomainArgs'] domain: Configures an optional DNS search domain block for the virtual network, controlling how guest hostnames are qualified and optionally whether they are registered only locally.
        :param pulumi.Input['NetworkForwardArgs'] forward: Configures forwarding for the virtual network, defining how traffic is connected to external networks (e.g. NAT, routed, bridge, macvtap).
        :param pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]] ips: Defines one or more IP address configurations for the network, including address, DHCP, and related options for IPv4 and/or IPv6.
               
               See: <https://libvirt.org/formatnetwork.html#addressing>
        :param pulumi.Input[_builtins.str] ipv6: Controls whether the network provides IPv6 support, as a boolean-like flag (`yes` or `no`).
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input['NetworkMacArgs'] mac: Enables configuring a fixed MAC address for the network bridge device.
        :param pulumi.Input['NetworkMetadataArgs'] metadata: Provides an arbitrary metadata container for the virtual network, typically used by higher-level tools; content is user-defined XML.
        :param pulumi.Input['NetworkMtuArgs'] mtu: Configures an MTU definition block for the virtual network; include this block only when you need to override the default MTU.
        :param pulumi.Input[_builtins.str] name: Sets the network’s name, which must be unique on the host and consist of alphanumeric characters plus ‘_’ or ‘-’.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]] port_groups: Defines one or more port groups that classify guest connections on this network, each with its own settings such as virtual port parameters or QoS.
               
               See: <https://libvirt.org/formatnetwork.html#portgroups>
        :param pulumi.Input['NetworkPortOptionsArgs'] port_options: Configures default per-port options for this virtual network, such as isolating traffic between guests connected to the same network.
        :param pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]] routes: Configures one or more static routes associated with this virtual network, informing the host about networks reachable via guests.
               
               See: <https://libvirt.org/formatnetwork.html#static-routes>
        :param pulumi.Input[_builtins.str] trust_guest_rx_filters: Controls whether the network as a whole trusts guests' receive-side filtering settings, corresponding to the yes/no trustGuestRxFilters flag on the network definition.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input['NetworkVirtualPortArgs'] virtual_port: Configures virtual port profile information for this port group, enabling integration with external network switching or SDN systems.
        :param pulumi.Input['NetworkVlanArgs'] vlan: Configures VLAN tagging behavior for this portgroup, allowing one or more VLAN tags to be applied to guest connections when the underlying network supports VLAN offload.
        """
        if autostart is not None:
            pulumi.set(__self__, "autostart", autostart)
        if bandwidth is not None:
            pulumi.set(__self__, "bandwidth", bandwidth)
        if bridge is not None:
            pulumi.set(__self__, "bridge", bridge)
        if dns is not None:
            pulumi.set(__self__, "dns", dns)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if forward is not None:
            pulumi.set(__self__, "forward", forward)
        if ips is not None:
            pulumi.set(__self__, "ips", ips)
        if ipv6 is not None:
            pulumi.set(__self__, "ipv6", ipv6)
        if mac is not None:
            pulumi.set(__self__, "mac", mac)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if mtu is not None:
            pulumi.set(__self__, "mtu", mtu)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if port_groups is not None:
            pulumi.set(__self__, "port_groups", port_groups)
        if port_options is not None:
            pulumi.set(__self__, "port_options", port_options)
        if routes is not None:
            pulumi.set(__self__, "routes", routes)
        if trust_guest_rx_filters is not None:
            pulumi.set(__self__, "trust_guest_rx_filters", trust_guest_rx_filters)
        if virtual_port is not None:
            pulumi.set(__self__, "virtual_port", virtual_port)
        if vlan is not None:
            pulumi.set(__self__, "vlan", vlan)

    @_builtins.property
    @pulumi.getter
    def autostart(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the network should be started automatically when the host boots
        """
        return pulumi.get(self, "autostart")

    @autostart.setter
    def autostart(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "autostart", value)

    @_builtins.property
    @pulumi.getter
    def bandwidth(self) -> Optional[pulumi.Input['NetworkBandwidthArgs']]:
        """
        Configures overall QoS bandwidth limits for the virtual network, enabling nested inbound/outbound rate settings when present.
        """
        return pulumi.get(self, "bandwidth")

    @bandwidth.setter
    def bandwidth(self, value: Optional[pulumi.Input['NetworkBandwidthArgs']]):
        pulumi.set(self, "bandwidth", value)

    @_builtins.property
    @pulumi.getter
    def bridge(self) -> Optional[pulumi.Input['NetworkBridgeArgs']]:
        return pulumi.get(self, "bridge")

    @bridge.setter
    def bridge(self, value: Optional[pulumi.Input['NetworkBridgeArgs']]):
        pulumi.set(self, "bridge", value)

    @_builtins.property
    @pulumi.getter
    def dns(self) -> Optional[pulumi.Input['NetworkDnsArgs']]:
        """
        Enables configuration of DNS services for the virtual network, including forwarders and static records. Presence of this block turns on DNS handling according to its child settings.
        """
        return pulumi.get(self, "dns")

    @dns.setter
    def dns(self, value: Optional[pulumi.Input['NetworkDnsArgs']]):
        pulumi.set(self, "dns", value)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input['NetworkDomainArgs']]:
        """
        Configures an optional DNS search domain block for the virtual network, controlling how guest hostnames are qualified and optionally whether they are registered only locally.
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input['NetworkDomainArgs']]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def forward(self) -> Optional[pulumi.Input['NetworkForwardArgs']]:
        """
        Configures forwarding for the virtual network, defining how traffic is connected to external networks (e.g. NAT, routed, bridge, macvtap).
        """
        return pulumi.get(self, "forward")

    @forward.setter
    def forward(self, value: Optional[pulumi.Input['NetworkForwardArgs']]):
        pulumi.set(self, "forward", value)

    @_builtins.property
    @pulumi.getter
    def ips(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]]]:
        """
        Defines one or more IP address configurations for the network, including address, DHCP, and related options for IPv4 and/or IPv6.

        See: <https://libvirt.org/formatnetwork.html#addressing>
        """
        return pulumi.get(self, "ips")

    @ips.setter
    def ips(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]]]):
        pulumi.set(self, "ips", value)

    @_builtins.property
    @pulumi.getter
    def ipv6(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Controls whether the network provides IPv6 support, as a boolean-like flag (`yes` or `no`).

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "ipv6")

    @ipv6.setter
    def ipv6(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ipv6", value)

    @_builtins.property
    @pulumi.getter
    def mac(self) -> Optional[pulumi.Input['NetworkMacArgs']]:
        """
        Enables configuring a fixed MAC address for the network bridge device.
        """
        return pulumi.get(self, "mac")

    @mac.setter
    def mac(self, value: Optional[pulumi.Input['NetworkMacArgs']]):
        pulumi.set(self, "mac", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input['NetworkMetadataArgs']]:
        """
        Provides an arbitrary metadata container for the virtual network, typically used by higher-level tools; content is user-defined XML.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input['NetworkMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def mtu(self) -> Optional[pulumi.Input['NetworkMtuArgs']]:
        """
        Configures an MTU definition block for the virtual network; include this block only when you need to override the default MTU.
        """
        return pulumi.get(self, "mtu")

    @mtu.setter
    def mtu(self, value: Optional[pulumi.Input['NetworkMtuArgs']]):
        pulumi.set(self, "mtu", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the network’s name, which must be unique on the host and consist of alphanumeric characters plus ‘_’ or ‘-’.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="portGroups")
    def port_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]]]:
        """
        Defines one or more port groups that classify guest connections on this network, each with its own settings such as virtual port parameters or QoS.

        See: <https://libvirt.org/formatnetwork.html#portgroups>
        """
        return pulumi.get(self, "port_groups")

    @port_groups.setter
    def port_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]]]):
        pulumi.set(self, "port_groups", value)

    @_builtins.property
    @pulumi.getter(name="portOptions")
    def port_options(self) -> Optional[pulumi.Input['NetworkPortOptionsArgs']]:
        """
        Configures default per-port options for this virtual network, such as isolating traffic between guests connected to the same network.
        """
        return pulumi.get(self, "port_options")

    @port_options.setter
    def port_options(self, value: Optional[pulumi.Input['NetworkPortOptionsArgs']]):
        pulumi.set(self, "port_options", value)

    @_builtins.property
    @pulumi.getter
    def routes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]]]:
        """
        Configures one or more static routes associated with this virtual network, informing the host about networks reachable via guests.

        See: <https://libvirt.org/formatnetwork.html#static-routes>
        """
        return pulumi.get(self, "routes")

    @routes.setter
    def routes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]]]):
        pulumi.set(self, "routes", value)

    @_builtins.property
    @pulumi.getter(name="trustGuestRxFilters")
    def trust_guest_rx_filters(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Controls whether the network as a whole trusts guests' receive-side filtering settings, corresponding to the yes/no trustGuestRxFilters flag on the network definition.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "trust_guest_rx_filters")

    @trust_guest_rx_filters.setter
    def trust_guest_rx_filters(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "trust_guest_rx_filters", value)

    @_builtins.property
    @pulumi.getter(name="virtualPort")
    def virtual_port(self) -> Optional[pulumi.Input['NetworkVirtualPortArgs']]:
        """
        Configures virtual port profile information for this port group, enabling integration with external network switching or SDN systems.
        """
        return pulumi.get(self, "virtual_port")

    @virtual_port.setter
    def virtual_port(self, value: Optional[pulumi.Input['NetworkVirtualPortArgs']]):
        pulumi.set(self, "virtual_port", value)

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> Optional[pulumi.Input['NetworkVlanArgs']]:
        """
        Configures VLAN tagging behavior for this portgroup, allowing one or more VLAN tags to be applied to guest connections when the underlying network supports VLAN offload.
        """
        return pulumi.get(self, "vlan")

    @vlan.setter
    def vlan(self, value: Optional[pulumi.Input['NetworkVlanArgs']]):
        pulumi.set(self, "vlan", value)


@pulumi.input_type
class _NetworkState:
    def __init__(__self__, *,
                 autostart: Optional[pulumi.Input[_builtins.bool]] = None,
                 bandwidth: Optional[pulumi.Input['NetworkBandwidthArgs']] = None,
                 bridge: Optional[pulumi.Input['NetworkBridgeArgs']] = None,
                 dns: Optional[pulumi.Input['NetworkDnsArgs']] = None,
                 domain: Optional[pulumi.Input['NetworkDomainArgs']] = None,
                 forward: Optional[pulumi.Input['NetworkForwardArgs']] = None,
                 ips: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]]] = None,
                 ipv6: Optional[pulumi.Input[_builtins.str]] = None,
                 mac: Optional[pulumi.Input['NetworkMacArgs']] = None,
                 metadata: Optional[pulumi.Input['NetworkMetadataArgs']] = None,
                 mtu: Optional[pulumi.Input['NetworkMtuArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port_groups: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]]] = None,
                 port_options: Optional[pulumi.Input['NetworkPortOptionsArgs']] = None,
                 routes: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]]] = None,
                 trust_guest_rx_filters: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 virtual_port: Optional[pulumi.Input['NetworkVirtualPortArgs']] = None,
                 vlan: Optional[pulumi.Input['NetworkVlanArgs']] = None):
        """
        Input properties used for looking up and filtering Network resources.
        :param pulumi.Input[_builtins.bool] autostart: Whether the network should be started automatically when the host boots
        :param pulumi.Input['NetworkBandwidthArgs'] bandwidth: Configures overall QoS bandwidth limits for the virtual network, enabling nested inbound/outbound rate settings when present.
        :param pulumi.Input['NetworkDnsArgs'] dns: Enables configuration of DNS services for the virtual network, including forwarders and static records. Presence of this block turns on DNS handling according to its child settings.
        :param pulumi.Input['NetworkDomainArgs'] domain: Configures an optional DNS search domain block for the virtual network, controlling how guest hostnames are qualified and optionally whether they are registered only locally.
        :param pulumi.Input['NetworkForwardArgs'] forward: Configures forwarding for the virtual network, defining how traffic is connected to external networks (e.g. NAT, routed, bridge, macvtap).
        :param pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]] ips: Defines one or more IP address configurations for the network, including address, DHCP, and related options for IPv4 and/or IPv6.
               
               See: <https://libvirt.org/formatnetwork.html#addressing>
        :param pulumi.Input[_builtins.str] ipv6: Controls whether the network provides IPv6 support, as a boolean-like flag (`yes` or `no`).
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input['NetworkMacArgs'] mac: Enables configuring a fixed MAC address for the network bridge device.
        :param pulumi.Input['NetworkMetadataArgs'] metadata: Provides an arbitrary metadata container for the virtual network, typically used by higher-level tools; content is user-defined XML.
        :param pulumi.Input['NetworkMtuArgs'] mtu: Configures an MTU definition block for the virtual network; include this block only when you need to override the default MTU.
        :param pulumi.Input[_builtins.str] name: Sets the network’s name, which must be unique on the host and consist of alphanumeric characters plus ‘_’ or ‘-’.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]] port_groups: Defines one or more port groups that classify guest connections on this network, each with its own settings such as virtual port parameters or QoS.
               
               See: <https://libvirt.org/formatnetwork.html#portgroups>
        :param pulumi.Input['NetworkPortOptionsArgs'] port_options: Configures default per-port options for this virtual network, such as isolating traffic between guests connected to the same network.
        :param pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]] routes: Configures one or more static routes associated with this virtual network, informing the host about networks reachable via guests.
               
               See: <https://libvirt.org/formatnetwork.html#static-routes>
        :param pulumi.Input[_builtins.str] trust_guest_rx_filters: Controls whether the network as a whole trusts guests' receive-side filtering settings, corresponding to the yes/no trustGuestRxFilters flag on the network definition.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[_builtins.str] uuid: Exposes the network's UUID as assigned by libvirt; this is read-only and computed, and uniquely identifies the virtual network on the host.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input['NetworkVirtualPortArgs'] virtual_port: Configures virtual port profile information for this port group, enabling integration with external network switching or SDN systems.
        :param pulumi.Input['NetworkVlanArgs'] vlan: Configures VLAN tagging behavior for this portgroup, allowing one or more VLAN tags to be applied to guest connections when the underlying network supports VLAN offload.
        """
        if autostart is not None:
            pulumi.set(__self__, "autostart", autostart)
        if bandwidth is not None:
            pulumi.set(__self__, "bandwidth", bandwidth)
        if bridge is not None:
            pulumi.set(__self__, "bridge", bridge)
        if dns is not None:
            pulumi.set(__self__, "dns", dns)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if forward is not None:
            pulumi.set(__self__, "forward", forward)
        if ips is not None:
            pulumi.set(__self__, "ips", ips)
        if ipv6 is not None:
            pulumi.set(__self__, "ipv6", ipv6)
        if mac is not None:
            pulumi.set(__self__, "mac", mac)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if mtu is not None:
            pulumi.set(__self__, "mtu", mtu)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if port_groups is not None:
            pulumi.set(__self__, "port_groups", port_groups)
        if port_options is not None:
            pulumi.set(__self__, "port_options", port_options)
        if routes is not None:
            pulumi.set(__self__, "routes", routes)
        if trust_guest_rx_filters is not None:
            pulumi.set(__self__, "trust_guest_rx_filters", trust_guest_rx_filters)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if virtual_port is not None:
            pulumi.set(__self__, "virtual_port", virtual_port)
        if vlan is not None:
            pulumi.set(__self__, "vlan", vlan)

    @_builtins.property
    @pulumi.getter
    def autostart(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the network should be started automatically when the host boots
        """
        return pulumi.get(self, "autostart")

    @autostart.setter
    def autostart(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "autostart", value)

    @_builtins.property
    @pulumi.getter
    def bandwidth(self) -> Optional[pulumi.Input['NetworkBandwidthArgs']]:
        """
        Configures overall QoS bandwidth limits for the virtual network, enabling nested inbound/outbound rate settings when present.
        """
        return pulumi.get(self, "bandwidth")

    @bandwidth.setter
    def bandwidth(self, value: Optional[pulumi.Input['NetworkBandwidthArgs']]):
        pulumi.set(self, "bandwidth", value)

    @_builtins.property
    @pulumi.getter
    def bridge(self) -> Optional[pulumi.Input['NetworkBridgeArgs']]:
        return pulumi.get(self, "bridge")

    @bridge.setter
    def bridge(self, value: Optional[pulumi.Input['NetworkBridgeArgs']]):
        pulumi.set(self, "bridge", value)

    @_builtins.property
    @pulumi.getter
    def dns(self) -> Optional[pulumi.Input['NetworkDnsArgs']]:
        """
        Enables configuration of DNS services for the virtual network, including forwarders and static records. Presence of this block turns on DNS handling according to its child settings.
        """
        return pulumi.get(self, "dns")

    @dns.setter
    def dns(self, value: Optional[pulumi.Input['NetworkDnsArgs']]):
        pulumi.set(self, "dns", value)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input['NetworkDomainArgs']]:
        """
        Configures an optional DNS search domain block for the virtual network, controlling how guest hostnames are qualified and optionally whether they are registered only locally.
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input['NetworkDomainArgs']]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def forward(self) -> Optional[pulumi.Input['NetworkForwardArgs']]:
        """
        Configures forwarding for the virtual network, defining how traffic is connected to external networks (e.g. NAT, routed, bridge, macvtap).
        """
        return pulumi.get(self, "forward")

    @forward.setter
    def forward(self, value: Optional[pulumi.Input['NetworkForwardArgs']]):
        pulumi.set(self, "forward", value)

    @_builtins.property
    @pulumi.getter
    def ips(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]]]:
        """
        Defines one or more IP address configurations for the network, including address, DHCP, and related options for IPv4 and/or IPv6.

        See: <https://libvirt.org/formatnetwork.html#addressing>
        """
        return pulumi.get(self, "ips")

    @ips.setter
    def ips(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkIpArgs']]]]):
        pulumi.set(self, "ips", value)

    @_builtins.property
    @pulumi.getter
    def ipv6(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Controls whether the network provides IPv6 support, as a boolean-like flag (`yes` or `no`).

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "ipv6")

    @ipv6.setter
    def ipv6(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ipv6", value)

    @_builtins.property
    @pulumi.getter
    def mac(self) -> Optional[pulumi.Input['NetworkMacArgs']]:
        """
        Enables configuring a fixed MAC address for the network bridge device.
        """
        return pulumi.get(self, "mac")

    @mac.setter
    def mac(self, value: Optional[pulumi.Input['NetworkMacArgs']]):
        pulumi.set(self, "mac", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input['NetworkMetadataArgs']]:
        """
        Provides an arbitrary metadata container for the virtual network, typically used by higher-level tools; content is user-defined XML.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input['NetworkMetadataArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def mtu(self) -> Optional[pulumi.Input['NetworkMtuArgs']]:
        """
        Configures an MTU definition block for the virtual network; include this block only when you need to override the default MTU.
        """
        return pulumi.get(self, "mtu")

    @mtu.setter
    def mtu(self, value: Optional[pulumi.Input['NetworkMtuArgs']]):
        pulumi.set(self, "mtu", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the network’s name, which must be unique on the host and consist of alphanumeric characters plus ‘_’ or ‘-’.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="portGroups")
    def port_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]]]:
        """
        Defines one or more port groups that classify guest connections on this network, each with its own settings such as virtual port parameters or QoS.

        See: <https://libvirt.org/formatnetwork.html#portgroups>
        """
        return pulumi.get(self, "port_groups")

    @port_groups.setter
    def port_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkPortGroupArgs']]]]):
        pulumi.set(self, "port_groups", value)

    @_builtins.property
    @pulumi.getter(name="portOptions")
    def port_options(self) -> Optional[pulumi.Input['NetworkPortOptionsArgs']]:
        """
        Configures default per-port options for this virtual network, such as isolating traffic between guests connected to the same network.
        """
        return pulumi.get(self, "port_options")

    @port_options.setter
    def port_options(self, value: Optional[pulumi.Input['NetworkPortOptionsArgs']]):
        pulumi.set(self, "port_options", value)

    @_builtins.property
    @pulumi.getter
    def routes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]]]:
        """
        Configures one or more static routes associated with this virtual network, informing the host about networks reachable via guests.

        See: <https://libvirt.org/formatnetwork.html#static-routes>
        """
        return pulumi.get(self, "routes")

    @routes.setter
    def routes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NetworkRouteArgs']]]]):
        pulumi.set(self, "routes", value)

    @_builtins.property
    @pulumi.getter(name="trustGuestRxFilters")
    def trust_guest_rx_filters(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Controls whether the network as a whole trusts guests' receive-side filtering settings, corresponding to the yes/no trustGuestRxFilters flag on the network definition.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "trust_guest_rx_filters")

    @trust_guest_rx_filters.setter
    def trust_guest_rx_filters(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "trust_guest_rx_filters", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Exposes the network's UUID as assigned by libvirt; this is read-only and computed, and uniquely identifies the virtual network on the host.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter(name="virtualPort")
    def virtual_port(self) -> Optional[pulumi.Input['NetworkVirtualPortArgs']]:
        """
        Configures virtual port profile information for this port group, enabling integration with external network switching or SDN systems.
        """
        return pulumi.get(self, "virtual_port")

    @virtual_port.setter
    def virtual_port(self, value: Optional[pulumi.Input['NetworkVirtualPortArgs']]):
        pulumi.set(self, "virtual_port", value)

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> Optional[pulumi.Input['NetworkVlanArgs']]:
        """
        Configures VLAN tagging behavior for this portgroup, allowing one or more VLAN tags to be applied to guest connections when the underlying network supports VLAN offload.
        """
        return pulumi.get(self, "vlan")

    @vlan.setter
    def vlan(self, value: Optional[pulumi.Input['NetworkVlanArgs']]):
        pulumi.set(self, "vlan", value)


@pulumi.type_token("libvirt:index/network:Network")
class Network(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 autostart: Optional[pulumi.Input[_builtins.bool]] = None,
                 bandwidth: Optional[pulumi.Input[Union['NetworkBandwidthArgs', 'NetworkBandwidthArgsDict']]] = None,
                 bridge: Optional[pulumi.Input[Union['NetworkBridgeArgs', 'NetworkBridgeArgsDict']]] = None,
                 dns: Optional[pulumi.Input[Union['NetworkDnsArgs', 'NetworkDnsArgsDict']]] = None,
                 domain: Optional[pulumi.Input[Union['NetworkDomainArgs', 'NetworkDomainArgsDict']]] = None,
                 forward: Optional[pulumi.Input[Union['NetworkForwardArgs', 'NetworkForwardArgsDict']]] = None,
                 ips: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkIpArgs', 'NetworkIpArgsDict']]]]] = None,
                 ipv6: Optional[pulumi.Input[_builtins.str]] = None,
                 mac: Optional[pulumi.Input[Union['NetworkMacArgs', 'NetworkMacArgsDict']]] = None,
                 metadata: Optional[pulumi.Input[Union['NetworkMetadataArgs', 'NetworkMetadataArgsDict']]] = None,
                 mtu: Optional[pulumi.Input[Union['NetworkMtuArgs', 'NetworkMtuArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port_groups: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkPortGroupArgs', 'NetworkPortGroupArgsDict']]]]] = None,
                 port_options: Optional[pulumi.Input[Union['NetworkPortOptionsArgs', 'NetworkPortOptionsArgsDict']]] = None,
                 routes: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkRouteArgs', 'NetworkRouteArgsDict']]]]] = None,
                 trust_guest_rx_filters: Optional[pulumi.Input[_builtins.str]] = None,
                 virtual_port: Optional[pulumi.Input[Union['NetworkVirtualPortArgs', 'NetworkVirtualPortArgsDict']]] = None,
                 vlan: Optional[pulumi.Input[Union['NetworkVlanArgs', 'NetworkVlanArgsDict']]] = None,
                 __props__=None):
        """
        Create a Network resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] autostart: Whether the network should be started automatically when the host boots
        :param pulumi.Input[Union['NetworkBandwidthArgs', 'NetworkBandwidthArgsDict']] bandwidth: Configures overall QoS bandwidth limits for the virtual network, enabling nested inbound/outbound rate settings when present.
        :param pulumi.Input[Union['NetworkDnsArgs', 'NetworkDnsArgsDict']] dns: Enables configuration of DNS services for the virtual network, including forwarders and static records. Presence of this block turns on DNS handling according to its child settings.
        :param pulumi.Input[Union['NetworkDomainArgs', 'NetworkDomainArgsDict']] domain: Configures an optional DNS search domain block for the virtual network, controlling how guest hostnames are qualified and optionally whether they are registered only locally.
        :param pulumi.Input[Union['NetworkForwardArgs', 'NetworkForwardArgsDict']] forward: Configures forwarding for the virtual network, defining how traffic is connected to external networks (e.g. NAT, routed, bridge, macvtap).
        :param pulumi.Input[Sequence[pulumi.Input[Union['NetworkIpArgs', 'NetworkIpArgsDict']]]] ips: Defines one or more IP address configurations for the network, including address, DHCP, and related options for IPv4 and/or IPv6.
               
               See: <https://libvirt.org/formatnetwork.html#addressing>
        :param pulumi.Input[_builtins.str] ipv6: Controls whether the network provides IPv6 support, as a boolean-like flag (`yes` or `no`).
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Union['NetworkMacArgs', 'NetworkMacArgsDict']] mac: Enables configuring a fixed MAC address for the network bridge device.
        :param pulumi.Input[Union['NetworkMetadataArgs', 'NetworkMetadataArgsDict']] metadata: Provides an arbitrary metadata container for the virtual network, typically used by higher-level tools; content is user-defined XML.
        :param pulumi.Input[Union['NetworkMtuArgs', 'NetworkMtuArgsDict']] mtu: Configures an MTU definition block for the virtual network; include this block only when you need to override the default MTU.
        :param pulumi.Input[_builtins.str] name: Sets the network’s name, which must be unique on the host and consist of alphanumeric characters plus ‘_’ or ‘-’.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Sequence[pulumi.Input[Union['NetworkPortGroupArgs', 'NetworkPortGroupArgsDict']]]] port_groups: Defines one or more port groups that classify guest connections on this network, each with its own settings such as virtual port parameters or QoS.
               
               See: <https://libvirt.org/formatnetwork.html#portgroups>
        :param pulumi.Input[Union['NetworkPortOptionsArgs', 'NetworkPortOptionsArgsDict']] port_options: Configures default per-port options for this virtual network, such as isolating traffic between guests connected to the same network.
        :param pulumi.Input[Sequence[pulumi.Input[Union['NetworkRouteArgs', 'NetworkRouteArgsDict']]]] routes: Configures one or more static routes associated with this virtual network, informing the host about networks reachable via guests.
               
               See: <https://libvirt.org/formatnetwork.html#static-routes>
        :param pulumi.Input[_builtins.str] trust_guest_rx_filters: Controls whether the network as a whole trusts guests' receive-side filtering settings, corresponding to the yes/no trustGuestRxFilters flag on the network definition.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Union['NetworkVirtualPortArgs', 'NetworkVirtualPortArgsDict']] virtual_port: Configures virtual port profile information for this port group, enabling integration with external network switching or SDN systems.
        :param pulumi.Input[Union['NetworkVlanArgs', 'NetworkVlanArgsDict']] vlan: Configures VLAN tagging behavior for this portgroup, allowing one or more VLAN tags to be applied to guest connections when the underlying network supports VLAN offload.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[NetworkArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Network resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param NetworkArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(NetworkArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 autostart: Optional[pulumi.Input[_builtins.bool]] = None,
                 bandwidth: Optional[pulumi.Input[Union['NetworkBandwidthArgs', 'NetworkBandwidthArgsDict']]] = None,
                 bridge: Optional[pulumi.Input[Union['NetworkBridgeArgs', 'NetworkBridgeArgsDict']]] = None,
                 dns: Optional[pulumi.Input[Union['NetworkDnsArgs', 'NetworkDnsArgsDict']]] = None,
                 domain: Optional[pulumi.Input[Union['NetworkDomainArgs', 'NetworkDomainArgsDict']]] = None,
                 forward: Optional[pulumi.Input[Union['NetworkForwardArgs', 'NetworkForwardArgsDict']]] = None,
                 ips: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkIpArgs', 'NetworkIpArgsDict']]]]] = None,
                 ipv6: Optional[pulumi.Input[_builtins.str]] = None,
                 mac: Optional[pulumi.Input[Union['NetworkMacArgs', 'NetworkMacArgsDict']]] = None,
                 metadata: Optional[pulumi.Input[Union['NetworkMetadataArgs', 'NetworkMetadataArgsDict']]] = None,
                 mtu: Optional[pulumi.Input[Union['NetworkMtuArgs', 'NetworkMtuArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port_groups: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkPortGroupArgs', 'NetworkPortGroupArgsDict']]]]] = None,
                 port_options: Optional[pulumi.Input[Union['NetworkPortOptionsArgs', 'NetworkPortOptionsArgsDict']]] = None,
                 routes: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkRouteArgs', 'NetworkRouteArgsDict']]]]] = None,
                 trust_guest_rx_filters: Optional[pulumi.Input[_builtins.str]] = None,
                 virtual_port: Optional[pulumi.Input[Union['NetworkVirtualPortArgs', 'NetworkVirtualPortArgsDict']]] = None,
                 vlan: Optional[pulumi.Input[Union['NetworkVlanArgs', 'NetworkVlanArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = NetworkArgs.__new__(NetworkArgs)

            __props__.__dict__["autostart"] = autostart
            __props__.__dict__["bandwidth"] = bandwidth
            __props__.__dict__["bridge"] = bridge
            __props__.__dict__["dns"] = dns
            __props__.__dict__["domain"] = domain
            __props__.__dict__["forward"] = forward
            __props__.__dict__["ips"] = ips
            __props__.__dict__["ipv6"] = ipv6
            __props__.__dict__["mac"] = mac
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["mtu"] = mtu
            __props__.__dict__["name"] = name
            __props__.__dict__["port_groups"] = port_groups
            __props__.__dict__["port_options"] = port_options
            __props__.__dict__["routes"] = routes
            __props__.__dict__["trust_guest_rx_filters"] = trust_guest_rx_filters
            __props__.__dict__["virtual_port"] = virtual_port
            __props__.__dict__["vlan"] = vlan
            __props__.__dict__["uuid"] = None
        super(Network, __self__).__init__(
            'libvirt:index/network:Network',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            autostart: Optional[pulumi.Input[_builtins.bool]] = None,
            bandwidth: Optional[pulumi.Input[Union['NetworkBandwidthArgs', 'NetworkBandwidthArgsDict']]] = None,
            bridge: Optional[pulumi.Input[Union['NetworkBridgeArgs', 'NetworkBridgeArgsDict']]] = None,
            dns: Optional[pulumi.Input[Union['NetworkDnsArgs', 'NetworkDnsArgsDict']]] = None,
            domain: Optional[pulumi.Input[Union['NetworkDomainArgs', 'NetworkDomainArgsDict']]] = None,
            forward: Optional[pulumi.Input[Union['NetworkForwardArgs', 'NetworkForwardArgsDict']]] = None,
            ips: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkIpArgs', 'NetworkIpArgsDict']]]]] = None,
            ipv6: Optional[pulumi.Input[_builtins.str]] = None,
            mac: Optional[pulumi.Input[Union['NetworkMacArgs', 'NetworkMacArgsDict']]] = None,
            metadata: Optional[pulumi.Input[Union['NetworkMetadataArgs', 'NetworkMetadataArgsDict']]] = None,
            mtu: Optional[pulumi.Input[Union['NetworkMtuArgs', 'NetworkMtuArgsDict']]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            port_groups: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkPortGroupArgs', 'NetworkPortGroupArgsDict']]]]] = None,
            port_options: Optional[pulumi.Input[Union['NetworkPortOptionsArgs', 'NetworkPortOptionsArgsDict']]] = None,
            routes: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NetworkRouteArgs', 'NetworkRouteArgsDict']]]]] = None,
            trust_guest_rx_filters: Optional[pulumi.Input[_builtins.str]] = None,
            uuid: Optional[pulumi.Input[_builtins.str]] = None,
            virtual_port: Optional[pulumi.Input[Union['NetworkVirtualPortArgs', 'NetworkVirtualPortArgsDict']]] = None,
            vlan: Optional[pulumi.Input[Union['NetworkVlanArgs', 'NetworkVlanArgsDict']]] = None) -> 'Network':
        """
        Get an existing Network resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] autostart: Whether the network should be started automatically when the host boots
        :param pulumi.Input[Union['NetworkBandwidthArgs', 'NetworkBandwidthArgsDict']] bandwidth: Configures overall QoS bandwidth limits for the virtual network, enabling nested inbound/outbound rate settings when present.
        :param pulumi.Input[Union['NetworkDnsArgs', 'NetworkDnsArgsDict']] dns: Enables configuration of DNS services for the virtual network, including forwarders and static records. Presence of this block turns on DNS handling according to its child settings.
        :param pulumi.Input[Union['NetworkDomainArgs', 'NetworkDomainArgsDict']] domain: Configures an optional DNS search domain block for the virtual network, controlling how guest hostnames are qualified and optionally whether they are registered only locally.
        :param pulumi.Input[Union['NetworkForwardArgs', 'NetworkForwardArgsDict']] forward: Configures forwarding for the virtual network, defining how traffic is connected to external networks (e.g. NAT, routed, bridge, macvtap).
        :param pulumi.Input[Sequence[pulumi.Input[Union['NetworkIpArgs', 'NetworkIpArgsDict']]]] ips: Defines one or more IP address configurations for the network, including address, DHCP, and related options for IPv4 and/or IPv6.
               
               See: <https://libvirt.org/formatnetwork.html#addressing>
        :param pulumi.Input[_builtins.str] ipv6: Controls whether the network provides IPv6 support, as a boolean-like flag (`yes` or `no`).
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Union['NetworkMacArgs', 'NetworkMacArgsDict']] mac: Enables configuring a fixed MAC address for the network bridge device.
        :param pulumi.Input[Union['NetworkMetadataArgs', 'NetworkMetadataArgsDict']] metadata: Provides an arbitrary metadata container for the virtual network, typically used by higher-level tools; content is user-defined XML.
        :param pulumi.Input[Union['NetworkMtuArgs', 'NetworkMtuArgsDict']] mtu: Configures an MTU definition block for the virtual network; include this block only when you need to override the default MTU.
        :param pulumi.Input[_builtins.str] name: Sets the network’s name, which must be unique on the host and consist of alphanumeric characters plus ‘_’ or ‘-’.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Sequence[pulumi.Input[Union['NetworkPortGroupArgs', 'NetworkPortGroupArgsDict']]]] port_groups: Defines one or more port groups that classify guest connections on this network, each with its own settings such as virtual port parameters or QoS.
               
               See: <https://libvirt.org/formatnetwork.html#portgroups>
        :param pulumi.Input[Union['NetworkPortOptionsArgs', 'NetworkPortOptionsArgsDict']] port_options: Configures default per-port options for this virtual network, such as isolating traffic between guests connected to the same network.
        :param pulumi.Input[Sequence[pulumi.Input[Union['NetworkRouteArgs', 'NetworkRouteArgsDict']]]] routes: Configures one or more static routes associated with this virtual network, informing the host about networks reachable via guests.
               
               See: <https://libvirt.org/formatnetwork.html#static-routes>
        :param pulumi.Input[_builtins.str] trust_guest_rx_filters: Controls whether the network as a whole trusts guests' receive-side filtering settings, corresponding to the yes/no trustGuestRxFilters flag on the network definition.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[_builtins.str] uuid: Exposes the network's UUID as assigned by libvirt; this is read-only and computed, and uniquely identifies the virtual network on the host.
               
               See: <https://libvirt.org/formatnetwork.html#general-metadata>
        :param pulumi.Input[Union['NetworkVirtualPortArgs', 'NetworkVirtualPortArgsDict']] virtual_port: Configures virtual port profile information for this port group, enabling integration with external network switching or SDN systems.
        :param pulumi.Input[Union['NetworkVlanArgs', 'NetworkVlanArgsDict']] vlan: Configures VLAN tagging behavior for this portgroup, allowing one or more VLAN tags to be applied to guest connections when the underlying network supports VLAN offload.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _NetworkState.__new__(_NetworkState)

        __props__.__dict__["autostart"] = autostart
        __props__.__dict__["bandwidth"] = bandwidth
        __props__.__dict__["bridge"] = bridge
        __props__.__dict__["dns"] = dns
        __props__.__dict__["domain"] = domain
        __props__.__dict__["forward"] = forward
        __props__.__dict__["ips"] = ips
        __props__.__dict__["ipv6"] = ipv6
        __props__.__dict__["mac"] = mac
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["mtu"] = mtu
        __props__.__dict__["name"] = name
        __props__.__dict__["port_groups"] = port_groups
        __props__.__dict__["port_options"] = port_options
        __props__.__dict__["routes"] = routes
        __props__.__dict__["trust_guest_rx_filters"] = trust_guest_rx_filters
        __props__.__dict__["uuid"] = uuid
        __props__.__dict__["virtual_port"] = virtual_port
        __props__.__dict__["vlan"] = vlan
        return Network(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def autostart(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the network should be started automatically when the host boots
        """
        return pulumi.get(self, "autostart")

    @_builtins.property
    @pulumi.getter
    def bandwidth(self) -> pulumi.Output[Optional['outputs.NetworkBandwidth']]:
        """
        Configures overall QoS bandwidth limits for the virtual network, enabling nested inbound/outbound rate settings when present.
        """
        return pulumi.get(self, "bandwidth")

    @_builtins.property
    @pulumi.getter
    def bridge(self) -> pulumi.Output[Optional['outputs.NetworkBridge']]:
        return pulumi.get(self, "bridge")

    @_builtins.property
    @pulumi.getter
    def dns(self) -> pulumi.Output[Optional['outputs.NetworkDns']]:
        """
        Enables configuration of DNS services for the virtual network, including forwarders and static records. Presence of this block turns on DNS handling according to its child settings.
        """
        return pulumi.get(self, "dns")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[Optional['outputs.NetworkDomain']]:
        """
        Configures an optional DNS search domain block for the virtual network, controlling how guest hostnames are qualified and optionally whether they are registered only locally.
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def forward(self) -> pulumi.Output[Optional['outputs.NetworkForward']]:
        """
        Configures forwarding for the virtual network, defining how traffic is connected to external networks (e.g. NAT, routed, bridge, macvtap).
        """
        return pulumi.get(self, "forward")

    @_builtins.property
    @pulumi.getter
    def ips(self) -> pulumi.Output[Optional[Sequence['outputs.NetworkIp']]]:
        """
        Defines one or more IP address configurations for the network, including address, DHCP, and related options for IPv4 and/or IPv6.

        See: <https://libvirt.org/formatnetwork.html#addressing>
        """
        return pulumi.get(self, "ips")

    @_builtins.property
    @pulumi.getter
    def ipv6(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Controls whether the network provides IPv6 support, as a boolean-like flag (`yes` or `no`).

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "ipv6")

    @_builtins.property
    @pulumi.getter
    def mac(self) -> pulumi.Output[Optional['outputs.NetworkMac']]:
        """
        Enables configuring a fixed MAC address for the network bridge device.
        """
        return pulumi.get(self, "mac")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional['outputs.NetworkMetadata']]:
        """
        Provides an arbitrary metadata container for the virtual network, typically used by higher-level tools; content is user-defined XML.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def mtu(self) -> pulumi.Output[Optional['outputs.NetworkMtu']]:
        """
        Configures an MTU definition block for the virtual network; include this block only when you need to override the default MTU.
        """
        return pulumi.get(self, "mtu")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Sets the network’s name, which must be unique on the host and consist of alphanumeric characters plus ‘_’ or ‘-’.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="portGroups")
    def port_groups(self) -> pulumi.Output[Optional[Sequence['outputs.NetworkPortGroup']]]:
        """
        Defines one or more port groups that classify guest connections on this network, each with its own settings such as virtual port parameters or QoS.

        See: <https://libvirt.org/formatnetwork.html#portgroups>
        """
        return pulumi.get(self, "port_groups")

    @_builtins.property
    @pulumi.getter(name="portOptions")
    def port_options(self) -> pulumi.Output[Optional['outputs.NetworkPortOptions']]:
        """
        Configures default per-port options for this virtual network, such as isolating traffic between guests connected to the same network.
        """
        return pulumi.get(self, "port_options")

    @_builtins.property
    @pulumi.getter
    def routes(self) -> pulumi.Output[Optional[Sequence['outputs.NetworkRoute']]]:
        """
        Configures one or more static routes associated with this virtual network, informing the host about networks reachable via guests.

        See: <https://libvirt.org/formatnetwork.html#static-routes>
        """
        return pulumi.get(self, "routes")

    @_builtins.property
    @pulumi.getter(name="trustGuestRxFilters")
    def trust_guest_rx_filters(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Controls whether the network as a whole trusts guests' receive-side filtering settings, corresponding to the yes/no trustGuestRxFilters flag on the network definition.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "trust_guest_rx_filters")

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> pulumi.Output[_builtins.str]:
        """
        Exposes the network's UUID as assigned by libvirt; this is read-only and computed, and uniquely identifies the virtual network on the host.

        See: <https://libvirt.org/formatnetwork.html#general-metadata>
        """
        return pulumi.get(self, "uuid")

    @_builtins.property
    @pulumi.getter(name="virtualPort")
    def virtual_port(self) -> pulumi.Output[Optional['outputs.NetworkVirtualPort']]:
        """
        Configures virtual port profile information for this port group, enabling integration with external network switching or SDN systems.
        """
        return pulumi.get(self, "virtual_port")

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> pulumi.Output[Optional['outputs.NetworkVlan']]:
        """
        Configures VLAN tagging behavior for this portgroup, allowing one or more VLAN tags to be applied to guest connections when the underlying network supports VLAN offload.
        """
        return pulumi.get(self, "vlan")

