# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['PoolArgs', 'Pool']

@pulumi.input_type
class PoolArgs:
    def __init__(__self__, *,
                 type: pulumi.Input[_builtins.str],
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 available_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 features: Optional[pulumi.Input['PoolFeaturesArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 refresh: Optional[pulumi.Input['PoolRefreshArgs']] = None,
                 source: Optional[pulumi.Input['PoolSourceArgs']] = None,
                 target: Optional[pulumi.Input['PoolTargetArgs']] = None):
        """
        The set of arguments for constructing a Pool resource.
        :param pulumi.Input[_builtins.str] type: Sets the storage pool backend type, such as "dir", "fs", "netfs", "logical", "disk", "iscsi", "scsi", "mpath", or "zfs", which determines which source/target sub-elements are valid.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-xml>
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit used for the storage_pool.allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] available_unit: Sets the unit used for the storage_pool.available value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for the storage_pool.capacity value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input['PoolFeaturesArgs'] features: Enables optional storage-pool-specific features such as copy-on-write behavior.
        :param pulumi.Input[_builtins.str] name: Sets the storage pool name, which must be unique on the host and is required when defining a pool.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input['PoolRefreshArgs'] refresh: Configures optional refresh behavior for the pool and its volumes, controlling how allocation statistics are recomputed.
        :param pulumi.Input['PoolSourceArgs'] source: Defines the source backing for the storage pool (e.g., device, host, directory, or network export), specific to the chosen pool type.
        :param pulumi.Input['PoolTargetArgs'] target: Configures the pool target section, which describes how the storage pool is exposed or mapped on the host (such as the target directory, block device, or other mapping details).
        """
        pulumi.set(__self__, "type", type)
        if allocation_unit is not None:
            pulumi.set(__self__, "allocation_unit", allocation_unit)
        if available_unit is not None:
            pulumi.set(__self__, "available_unit", available_unit)
        if capacity_unit is not None:
            pulumi.set(__self__, "capacity_unit", capacity_unit)
        if features is not None:
            pulumi.set(__self__, "features", features)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if refresh is not None:
            pulumi.set(__self__, "refresh", refresh)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if target is not None:
            pulumi.set(__self__, "target", target)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        Sets the storage pool backend type, such as "dir", "fs", "netfs", "logical", "disk", "iscsi", "scsi", "mpath", or "zfs", which determines which source/target sub-elements are valid.

        See: <https://libvirt.org/formatstorage.html#storage-pool-xml>
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="allocationUnit")
    def allocation_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "allocation_unit")

    @allocation_unit.setter
    def allocation_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "allocation_unit", value)

    @_builtins.property
    @pulumi.getter(name="availableUnit")
    def available_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.available value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "available_unit")

    @available_unit.setter
    def available_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "available_unit", value)

    @_builtins.property
    @pulumi.getter(name="capacityUnit")
    def capacity_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.capacity value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "capacity_unit")

    @capacity_unit.setter
    def capacity_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "capacity_unit", value)

    @_builtins.property
    @pulumi.getter
    def features(self) -> Optional[pulumi.Input['PoolFeaturesArgs']]:
        """
        Enables optional storage-pool-specific features such as copy-on-write behavior.
        """
        return pulumi.get(self, "features")

    @features.setter
    def features(self, value: Optional[pulumi.Input['PoolFeaturesArgs']]):
        pulumi.set(self, "features", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the storage pool name, which must be unique on the host and is required when defining a pool.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def refresh(self) -> Optional[pulumi.Input['PoolRefreshArgs']]:
        """
        Configures optional refresh behavior for the pool and its volumes, controlling how allocation statistics are recomputed.
        """
        return pulumi.get(self, "refresh")

    @refresh.setter
    def refresh(self, value: Optional[pulumi.Input['PoolRefreshArgs']]):
        pulumi.set(self, "refresh", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> Optional[pulumi.Input['PoolSourceArgs']]:
        """
        Defines the source backing for the storage pool (e.g., device, host, directory, or network export), specific to the chosen pool type.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: Optional[pulumi.Input['PoolSourceArgs']]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def target(self) -> Optional[pulumi.Input['PoolTargetArgs']]:
        """
        Configures the pool target section, which describes how the storage pool is exposed or mapped on the host (such as the target directory, block device, or other mapping details).
        """
        return pulumi.get(self, "target")

    @target.setter
    def target(self, value: Optional[pulumi.Input['PoolTargetArgs']]):
        pulumi.set(self, "target", value)


@pulumi.input_type
class _PoolState:
    def __init__(__self__, *,
                 allocation: Optional[pulumi.Input[_builtins.float]] = None,
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 available: Optional[pulumi.Input[_builtins.float]] = None,
                 available_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 capacity: Optional[pulumi.Input[_builtins.float]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 features: Optional[pulumi.Input['PoolFeaturesArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 refresh: Optional[pulumi.Input['PoolRefreshArgs']] = None,
                 source: Optional[pulumi.Input['PoolSourceArgs']] = None,
                 target: Optional[pulumi.Input['PoolTargetArgs']] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Pool resources.
        :param pulumi.Input[_builtins.float] allocation: Exposes the current amount of space in the pool that is allocated to volumes; value is computed by libvirt and expressed in the unit indicated by storage_pool.allocation_unit.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit used for the storage_pool.allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.float] available: Exposes the currently available (free) space in the pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.available_unit.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] available_unit: Sets the unit used for the storage_pool.available value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.float] capacity: Exposes the total logical capacity of the storage pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.capacity_unit.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for the storage_pool.capacity value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input['PoolFeaturesArgs'] features: Enables optional storage-pool-specific features such as copy-on-write behavior.
        :param pulumi.Input[_builtins.str] name: Sets the storage pool name, which must be unique on the host and is required when defining a pool.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input['PoolRefreshArgs'] refresh: Configures optional refresh behavior for the pool and its volumes, controlling how allocation statistics are recomputed.
        :param pulumi.Input['PoolSourceArgs'] source: Defines the source backing for the storage pool (e.g., device, host, directory, or network export), specific to the chosen pool type.
        :param pulumi.Input['PoolTargetArgs'] target: Configures the pool target section, which describes how the storage pool is exposed or mapped on the host (such as the target directory, block device, or other mapping details).
        :param pulumi.Input[_builtins.str] type: Sets the storage pool backend type, such as "dir", "fs", "netfs", "logical", "disk", "iscsi", "scsi", "mpath", or "zfs", which determines which source/target sub-elements are valid.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-xml>
        :param pulumi.Input[_builtins.str] uuid: Exposes the libvirt-assigned UUID of the storage pool; if not specified by the user, it is generated and managed by libvirt.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        if allocation is not None:
            pulumi.set(__self__, "allocation", allocation)
        if allocation_unit is not None:
            pulumi.set(__self__, "allocation_unit", allocation_unit)
        if available is not None:
            pulumi.set(__self__, "available", available)
        if available_unit is not None:
            pulumi.set(__self__, "available_unit", available_unit)
        if capacity is not None:
            pulumi.set(__self__, "capacity", capacity)
        if capacity_unit is not None:
            pulumi.set(__self__, "capacity_unit", capacity_unit)
        if features is not None:
            pulumi.set(__self__, "features", features)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if refresh is not None:
            pulumi.set(__self__, "refresh", refresh)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if target is not None:
            pulumi.set(__self__, "target", target)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)

    @_builtins.property
    @pulumi.getter
    def allocation(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exposes the current amount of space in the pool that is allocated to volumes; value is computed by libvirt and expressed in the unit indicated by storage_pool.allocation_unit.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "allocation")

    @allocation.setter
    def allocation(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "allocation", value)

    @_builtins.property
    @pulumi.getter(name="allocationUnit")
    def allocation_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "allocation_unit")

    @allocation_unit.setter
    def allocation_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "allocation_unit", value)

    @_builtins.property
    @pulumi.getter
    def available(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exposes the currently available (free) space in the pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.available_unit.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "available")

    @available.setter
    def available(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "available", value)

    @_builtins.property
    @pulumi.getter(name="availableUnit")
    def available_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.available value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "available_unit")

    @available_unit.setter
    def available_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "available_unit", value)

    @_builtins.property
    @pulumi.getter
    def capacity(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exposes the total logical capacity of the storage pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.capacity_unit.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "capacity")

    @capacity.setter
    def capacity(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "capacity", value)

    @_builtins.property
    @pulumi.getter(name="capacityUnit")
    def capacity_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.capacity value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "capacity_unit")

    @capacity_unit.setter
    def capacity_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "capacity_unit", value)

    @_builtins.property
    @pulumi.getter
    def features(self) -> Optional[pulumi.Input['PoolFeaturesArgs']]:
        """
        Enables optional storage-pool-specific features such as copy-on-write behavior.
        """
        return pulumi.get(self, "features")

    @features.setter
    def features(self, value: Optional[pulumi.Input['PoolFeaturesArgs']]):
        pulumi.set(self, "features", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the storage pool name, which must be unique on the host and is required when defining a pool.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def refresh(self) -> Optional[pulumi.Input['PoolRefreshArgs']]:
        """
        Configures optional refresh behavior for the pool and its volumes, controlling how allocation statistics are recomputed.
        """
        return pulumi.get(self, "refresh")

    @refresh.setter
    def refresh(self, value: Optional[pulumi.Input['PoolRefreshArgs']]):
        pulumi.set(self, "refresh", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> Optional[pulumi.Input['PoolSourceArgs']]:
        """
        Defines the source backing for the storage pool (e.g., device, host, directory, or network export), specific to the chosen pool type.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: Optional[pulumi.Input['PoolSourceArgs']]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def target(self) -> Optional[pulumi.Input['PoolTargetArgs']]:
        """
        Configures the pool target section, which describes how the storage pool is exposed or mapped on the host (such as the target directory, block device, or other mapping details).
        """
        return pulumi.get(self, "target")

    @target.setter
    def target(self, value: Optional[pulumi.Input['PoolTargetArgs']]):
        pulumi.set(self, "target", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the storage pool backend type, such as "dir", "fs", "netfs", "logical", "disk", "iscsi", "scsi", "mpath", or "zfs", which determines which source/target sub-elements are valid.

        See: <https://libvirt.org/formatstorage.html#storage-pool-xml>
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Exposes the libvirt-assigned UUID of the storage pool; if not specified by the user, it is generated and managed by libvirt.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)


@pulumi.type_token("libvirt:index/pool:Pool")
class Pool(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 available_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 features: Optional[pulumi.Input[Union['PoolFeaturesArgs', 'PoolFeaturesArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 refresh: Optional[pulumi.Input[Union['PoolRefreshArgs', 'PoolRefreshArgsDict']]] = None,
                 source: Optional[pulumi.Input[Union['PoolSourceArgs', 'PoolSourceArgsDict']]] = None,
                 target: Optional[pulumi.Input[Union['PoolTargetArgs', 'PoolTargetArgsDict']]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Pool resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit used for the storage_pool.allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] available_unit: Sets the unit used for the storage_pool.available value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for the storage_pool.capacity value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[Union['PoolFeaturesArgs', 'PoolFeaturesArgsDict']] features: Enables optional storage-pool-specific features such as copy-on-write behavior.
        :param pulumi.Input[_builtins.str] name: Sets the storage pool name, which must be unique on the host and is required when defining a pool.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[Union['PoolRefreshArgs', 'PoolRefreshArgsDict']] refresh: Configures optional refresh behavior for the pool and its volumes, controlling how allocation statistics are recomputed.
        :param pulumi.Input[Union['PoolSourceArgs', 'PoolSourceArgsDict']] source: Defines the source backing for the storage pool (e.g., device, host, directory, or network export), specific to the chosen pool type.
        :param pulumi.Input[Union['PoolTargetArgs', 'PoolTargetArgsDict']] target: Configures the pool target section, which describes how the storage pool is exposed or mapped on the host (such as the target directory, block device, or other mapping details).
        :param pulumi.Input[_builtins.str] type: Sets the storage pool backend type, such as "dir", "fs", "netfs", "logical", "disk", "iscsi", "scsi", "mpath", or "zfs", which determines which source/target sub-elements are valid.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-xml>
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PoolArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Pool resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PoolArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PoolArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 available_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 features: Optional[pulumi.Input[Union['PoolFeaturesArgs', 'PoolFeaturesArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 refresh: Optional[pulumi.Input[Union['PoolRefreshArgs', 'PoolRefreshArgsDict']]] = None,
                 source: Optional[pulumi.Input[Union['PoolSourceArgs', 'PoolSourceArgsDict']]] = None,
                 target: Optional[pulumi.Input[Union['PoolTargetArgs', 'PoolTargetArgsDict']]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PoolArgs.__new__(PoolArgs)

            __props__.__dict__["allocation_unit"] = allocation_unit
            __props__.__dict__["available_unit"] = available_unit
            __props__.__dict__["capacity_unit"] = capacity_unit
            __props__.__dict__["features"] = features
            __props__.__dict__["name"] = name
            __props__.__dict__["refresh"] = refresh
            __props__.__dict__["source"] = source
            __props__.__dict__["target"] = target
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["allocation"] = None
            __props__.__dict__["available"] = None
            __props__.__dict__["capacity"] = None
            __props__.__dict__["uuid"] = None
        super(Pool, __self__).__init__(
            'libvirt:index/pool:Pool',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allocation: Optional[pulumi.Input[_builtins.float]] = None,
            allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
            available: Optional[pulumi.Input[_builtins.float]] = None,
            available_unit: Optional[pulumi.Input[_builtins.str]] = None,
            capacity: Optional[pulumi.Input[_builtins.float]] = None,
            capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
            features: Optional[pulumi.Input[Union['PoolFeaturesArgs', 'PoolFeaturesArgsDict']]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            refresh: Optional[pulumi.Input[Union['PoolRefreshArgs', 'PoolRefreshArgsDict']]] = None,
            source: Optional[pulumi.Input[Union['PoolSourceArgs', 'PoolSourceArgsDict']]] = None,
            target: Optional[pulumi.Input[Union['PoolTargetArgs', 'PoolTargetArgsDict']]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None,
            uuid: Optional[pulumi.Input[_builtins.str]] = None) -> 'Pool':
        """
        Get an existing Pool resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] allocation: Exposes the current amount of space in the pool that is allocated to volumes; value is computed by libvirt and expressed in the unit indicated by storage_pool.allocation_unit.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit used for the storage_pool.allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.float] available: Exposes the currently available (free) space in the pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.available_unit.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] available_unit: Sets the unit used for the storage_pool.available value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.float] capacity: Exposes the total logical capacity of the storage pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.capacity_unit.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for the storage_pool.capacity value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[Union['PoolFeaturesArgs', 'PoolFeaturesArgsDict']] features: Enables optional storage-pool-specific features such as copy-on-write behavior.
        :param pulumi.Input[_builtins.str] name: Sets the storage pool name, which must be unique on the host and is required when defining a pool.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        :param pulumi.Input[Union['PoolRefreshArgs', 'PoolRefreshArgsDict']] refresh: Configures optional refresh behavior for the pool and its volumes, controlling how allocation statistics are recomputed.
        :param pulumi.Input[Union['PoolSourceArgs', 'PoolSourceArgsDict']] source: Defines the source backing for the storage pool (e.g., device, host, directory, or network export), specific to the chosen pool type.
        :param pulumi.Input[Union['PoolTargetArgs', 'PoolTargetArgsDict']] target: Configures the pool target section, which describes how the storage pool is exposed or mapped on the host (such as the target directory, block device, or other mapping details).
        :param pulumi.Input[_builtins.str] type: Sets the storage pool backend type, such as "dir", "fs", "netfs", "logical", "disk", "iscsi", "scsi", "mpath", or "zfs", which determines which source/target sub-elements are valid.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-xml>
        :param pulumi.Input[_builtins.str] uuid: Exposes the libvirt-assigned UUID of the storage pool; if not specified by the user, it is generated and managed by libvirt.
               
               See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PoolState.__new__(_PoolState)

        __props__.__dict__["allocation"] = allocation
        __props__.__dict__["allocation_unit"] = allocation_unit
        __props__.__dict__["available"] = available
        __props__.__dict__["available_unit"] = available_unit
        __props__.__dict__["capacity"] = capacity
        __props__.__dict__["capacity_unit"] = capacity_unit
        __props__.__dict__["features"] = features
        __props__.__dict__["name"] = name
        __props__.__dict__["refresh"] = refresh
        __props__.__dict__["source"] = source
        __props__.__dict__["target"] = target
        __props__.__dict__["type"] = type
        __props__.__dict__["uuid"] = uuid
        return Pool(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def allocation(self) -> pulumi.Output[_builtins.float]:
        """
        Exposes the current amount of space in the pool that is allocated to volumes; value is computed by libvirt and expressed in the unit indicated by storage_pool.allocation_unit.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "allocation")

    @_builtins.property
    @pulumi.getter(name="allocationUnit")
    def allocation_unit(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "allocation_unit")

    @_builtins.property
    @pulumi.getter
    def available(self) -> pulumi.Output[_builtins.float]:
        """
        Exposes the currently available (free) space in the pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.available_unit.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "available")

    @_builtins.property
    @pulumi.getter(name="availableUnit")
    def available_unit(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.available value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "available_unit")

    @_builtins.property
    @pulumi.getter
    def capacity(self) -> pulumi.Output[_builtins.float]:
        """
        Exposes the total logical capacity of the storage pool; value is computed by libvirt and expressed in the unit indicated by storage_pool.capacity_unit.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "capacity")

    @_builtins.property
    @pulumi.getter(name="capacityUnit")
    def capacity_unit(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the unit used for the storage_pool.capacity value (for example, "bytes", "KiB", "MiB", "GiB"); if unset, libvirt’s default unit (typically bytes) is used.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "capacity_unit")

    @_builtins.property
    @pulumi.getter
    def features(self) -> pulumi.Output[Optional['outputs.PoolFeatures']]:
        """
        Enables optional storage-pool-specific features such as copy-on-write behavior.
        """
        return pulumi.get(self, "features")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Sets the storage pool name, which must be unique on the host and is required when defining a pool.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def refresh(self) -> pulumi.Output[Optional['outputs.PoolRefresh']]:
        """
        Configures optional refresh behavior for the pool and its volumes, controlling how allocation statistics are recomputed.
        """
        return pulumi.get(self, "refresh")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[Optional['outputs.PoolSource']]:
        """
        Defines the source backing for the storage pool (e.g., device, host, directory, or network export), specific to the chosen pool type.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def target(self) -> pulumi.Output[Optional['outputs.PoolTarget']]:
        """
        Configures the pool target section, which describes how the storage pool is exposed or mapped on the host (such as the target directory, block device, or other mapping details).
        """
        return pulumi.get(self, "target")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        Sets the storage pool backend type, such as "dir", "fs", "netfs", "logical", "disk", "iscsi", "scsi", "mpath", or "zfs", which determines which source/target sub-elements are valid.

        See: <https://libvirt.org/formatstorage.html#storage-pool-xml>
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> pulumi.Output[_builtins.str]:
        """
        Exposes the libvirt-assigned UUID of the storage pool; if not specified by the user, it is generated and managed by libvirt.

        See: <https://libvirt.org/formatstorage.html#storage-pool-general-metadata>
        """
        return pulumi.get(self, "uuid")

