# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['VolumeArgs', 'Volume']

@pulumi.input_type
class VolumeArgs:
    def __init__(__self__, *,
                 pool: pulumi.Input[_builtins.str],
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 backing_store: Optional[pulumi.Input['VolumeBackingStoreArgs']] = None,
                 capacity: Optional[pulumi.Input[_builtins.float]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 create: Optional[pulumi.Input['VolumeCreateArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 physical_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 target: Optional[pulumi.Input['VolumeTargetArgs']] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Volume resource.
        :param pulumi.Input[_builtins.str] pool: Name of the storage pool where the volume will be created
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit for the allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if omitted, libvirt uses its default unit semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input['VolumeBackingStoreArgs'] backing_store: Configures an optional backing store volume for copy-on-write images, enabling layered storage where this volume records changes on top of another image.
        :param pulumi.Input[_builtins.float] capacity: Volume capacity in bytes (required unless using create.content)
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for `capacity` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input['VolumeCreateArgs'] create: Volume creation options for initializing volume content from external sources
        :param pulumi.Input[_builtins.str] name: Sets the volume name, which must be unique within the containing pool (for disk pools, often derived from a device path plus partition index).
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] physical_unit: Sets the unit used for `physical` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] type: Sets the actual storage volume type reported by libvirt (for example `file`, `block`, `dir`, `network`, `netdir`, or `ploop`), matching the `type` attribute libvirt exposes for the volume; the value is user-provided and should be consistent with the underlying storage backend.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-xml>
        """
        pulumi.set(__self__, "pool", pool)
        if allocation_unit is not None:
            pulumi.set(__self__, "allocation_unit", allocation_unit)
        if backing_store is not None:
            pulumi.set(__self__, "backing_store", backing_store)
        if capacity is not None:
            pulumi.set(__self__, "capacity", capacity)
        if capacity_unit is not None:
            pulumi.set(__self__, "capacity_unit", capacity_unit)
        if create is not None:
            pulumi.set(__self__, "create", create)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if physical_unit is not None:
            pulumi.set(__self__, "physical_unit", physical_unit)
        if target is not None:
            pulumi.set(__self__, "target", target)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def pool(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the storage pool where the volume will be created
        """
        return pulumi.get(self, "pool")

    @pool.setter
    def pool(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "pool", value)

    @_builtins.property
    @pulumi.getter(name="allocationUnit")
    def allocation_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit for the allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if omitted, libvirt uses its default unit semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "allocation_unit")

    @allocation_unit.setter
    def allocation_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "allocation_unit", value)

    @_builtins.property
    @pulumi.getter(name="backingStore")
    def backing_store(self) -> Optional[pulumi.Input['VolumeBackingStoreArgs']]:
        """
        Configures an optional backing store volume for copy-on-write images, enabling layered storage where this volume records changes on top of another image.
        """
        return pulumi.get(self, "backing_store")

    @backing_store.setter
    def backing_store(self, value: Optional[pulumi.Input['VolumeBackingStoreArgs']]):
        pulumi.set(self, "backing_store", value)

    @_builtins.property
    @pulumi.getter
    def capacity(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Volume capacity in bytes (required unless using create.content)
        """
        return pulumi.get(self, "capacity")

    @capacity.setter
    def capacity(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "capacity", value)

    @_builtins.property
    @pulumi.getter(name="capacityUnit")
    def capacity_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for `capacity` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "capacity_unit")

    @capacity_unit.setter
    def capacity_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "capacity_unit", value)

    @_builtins.property
    @pulumi.getter
    def create(self) -> Optional[pulumi.Input['VolumeCreateArgs']]:
        """
        Volume creation options for initializing volume content from external sources
        """
        return pulumi.get(self, "create")

    @create.setter
    def create(self, value: Optional[pulumi.Input['VolumeCreateArgs']]):
        pulumi.set(self, "create", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the volume name, which must be unique within the containing pool (for disk pools, often derived from a device path plus partition index).

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="physicalUnit")
    def physical_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for `physical` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "physical_unit")

    @physical_unit.setter
    def physical_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "physical_unit", value)

    @_builtins.property
    @pulumi.getter
    def target(self) -> Optional[pulumi.Input['VolumeTargetArgs']]:
        return pulumi.get(self, "target")

    @target.setter
    def target(self, value: Optional[pulumi.Input['VolumeTargetArgs']]):
        pulumi.set(self, "target", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the actual storage volume type reported by libvirt (for example `file`, `block`, `dir`, `network`, `netdir`, or `ploop`), matching the `type` attribute libvirt exposes for the volume; the value is user-provided and should be consistent with the underlying storage backend.

        See: <https://libvirt.org/formatstorage.html#storage-volume-xml>
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.input_type
class _VolumeState:
    def __init__(__self__, *,
                 allocation: Optional[pulumi.Input[_builtins.float]] = None,
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 backing_store: Optional[pulumi.Input['VolumeBackingStoreArgs']] = None,
                 capacity: Optional[pulumi.Input[_builtins.float]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 create: Optional[pulumi.Input['VolumeCreateArgs']] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 physical: Optional[pulumi.Input[_builtins.float]] = None,
                 physical_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 pool: Optional[pulumi.Input[_builtins.str]] = None,
                 target: Optional[pulumi.Input['VolumeTargetArgs']] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Volume resources.
        :param pulumi.Input[_builtins.float] allocation: Reports the currently allocated space for the volume (in the unit specified by allocation_unit), which may be less than the volume capacity for sparse formats.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit for the allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if omitted, libvirt uses its default unit semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input['VolumeBackingStoreArgs'] backing_store: Configures an optional backing store volume for copy-on-write images, enabling layered storage where this volume records changes on top of another image.
        :param pulumi.Input[_builtins.float] capacity: Volume capacity in bytes (required unless using create.content)
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for `capacity` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input['VolumeCreateArgs'] create: Volume creation options for initializing volume content from external sources
        :param pulumi.Input[_builtins.str] key: Exposes the libvirt-assigned unique key identifying this volume within the pool, typically derived from the host path or backend identifier.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] name: Sets the volume name, which must be unique within the containing pool (for disk pools, often derived from a device path plus partition index).
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] path: Volume path on the host filesystem (same as target.path)
        :param pulumi.Input[_builtins.float] physical: Reports the actual physical space currently used by the volume on the underlying storage, as computed by libvirt.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] physical_unit: Sets the unit used for `physical` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] pool: Name of the storage pool where the volume will be created
        :param pulumi.Input[_builtins.str] type: Sets the actual storage volume type reported by libvirt (for example `file`, `block`, `dir`, `network`, `netdir`, or `ploop`), matching the `type` attribute libvirt exposes for the volume; the value is user-provided and should be consistent with the underlying storage backend.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-xml>
        """
        if allocation is not None:
            pulumi.set(__self__, "allocation", allocation)
        if allocation_unit is not None:
            pulumi.set(__self__, "allocation_unit", allocation_unit)
        if backing_store is not None:
            pulumi.set(__self__, "backing_store", backing_store)
        if capacity is not None:
            pulumi.set(__self__, "capacity", capacity)
        if capacity_unit is not None:
            pulumi.set(__self__, "capacity_unit", capacity_unit)
        if create is not None:
            pulumi.set(__self__, "create", create)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if physical is not None:
            pulumi.set(__self__, "physical", physical)
        if physical_unit is not None:
            pulumi.set(__self__, "physical_unit", physical_unit)
        if pool is not None:
            pulumi.set(__self__, "pool", pool)
        if target is not None:
            pulumi.set(__self__, "target", target)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def allocation(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Reports the currently allocated space for the volume (in the unit specified by allocation_unit), which may be less than the volume capacity for sparse formats.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "allocation")

    @allocation.setter
    def allocation(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "allocation", value)

    @_builtins.property
    @pulumi.getter(name="allocationUnit")
    def allocation_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit for the allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if omitted, libvirt uses its default unit semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "allocation_unit")

    @allocation_unit.setter
    def allocation_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "allocation_unit", value)

    @_builtins.property
    @pulumi.getter(name="backingStore")
    def backing_store(self) -> Optional[pulumi.Input['VolumeBackingStoreArgs']]:
        """
        Configures an optional backing store volume for copy-on-write images, enabling layered storage where this volume records changes on top of another image.
        """
        return pulumi.get(self, "backing_store")

    @backing_store.setter
    def backing_store(self, value: Optional[pulumi.Input['VolumeBackingStoreArgs']]):
        pulumi.set(self, "backing_store", value)

    @_builtins.property
    @pulumi.getter
    def capacity(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Volume capacity in bytes (required unless using create.content)
        """
        return pulumi.get(self, "capacity")

    @capacity.setter
    def capacity(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "capacity", value)

    @_builtins.property
    @pulumi.getter(name="capacityUnit")
    def capacity_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for `capacity` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "capacity_unit")

    @capacity_unit.setter
    def capacity_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "capacity_unit", value)

    @_builtins.property
    @pulumi.getter
    def create(self) -> Optional[pulumi.Input['VolumeCreateArgs']]:
        """
        Volume creation options for initializing volume content from external sources
        """
        return pulumi.get(self, "create")

    @create.setter
    def create(self, value: Optional[pulumi.Input['VolumeCreateArgs']]):
        pulumi.set(self, "create", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Exposes the libvirt-assigned unique key identifying this volume within the pool, typically derived from the host path or backend identifier.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the volume name, which must be unique within the containing pool (for disk pools, often derived from a device path plus partition index).

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Volume path on the host filesystem (same as target.path)
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def physical(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Reports the actual physical space currently used by the volume on the underlying storage, as computed by libvirt.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "physical")

    @physical.setter
    def physical(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "physical", value)

    @_builtins.property
    @pulumi.getter(name="physicalUnit")
    def physical_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the unit used for `physical` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "physical_unit")

    @physical_unit.setter
    def physical_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "physical_unit", value)

    @_builtins.property
    @pulumi.getter
    def pool(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the storage pool where the volume will be created
        """
        return pulumi.get(self, "pool")

    @pool.setter
    def pool(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "pool", value)

    @_builtins.property
    @pulumi.getter
    def target(self) -> Optional[pulumi.Input['VolumeTargetArgs']]:
        return pulumi.get(self, "target")

    @target.setter
    def target(self, value: Optional[pulumi.Input['VolumeTargetArgs']]):
        pulumi.set(self, "target", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the actual storage volume type reported by libvirt (for example `file`, `block`, `dir`, `network`, `netdir`, or `ploop`), matching the `type` attribute libvirt exposes for the volume; the value is user-provided and should be consistent with the underlying storage backend.

        See: <https://libvirt.org/formatstorage.html#storage-volume-xml>
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.type_token("libvirt:index/volume:Volume")
class Volume(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 backing_store: Optional[pulumi.Input[Union['VolumeBackingStoreArgs', 'VolumeBackingStoreArgsDict']]] = None,
                 capacity: Optional[pulumi.Input[_builtins.float]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 create: Optional[pulumi.Input[Union['VolumeCreateArgs', 'VolumeCreateArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 physical_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 pool: Optional[pulumi.Input[_builtins.str]] = None,
                 target: Optional[pulumi.Input[Union['VolumeTargetArgs', 'VolumeTargetArgsDict']]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Volume resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit for the allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if omitted, libvirt uses its default unit semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[Union['VolumeBackingStoreArgs', 'VolumeBackingStoreArgsDict']] backing_store: Configures an optional backing store volume for copy-on-write images, enabling layered storage where this volume records changes on top of another image.
        :param pulumi.Input[_builtins.float] capacity: Volume capacity in bytes (required unless using create.content)
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for `capacity` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[Union['VolumeCreateArgs', 'VolumeCreateArgsDict']] create: Volume creation options for initializing volume content from external sources
        :param pulumi.Input[_builtins.str] name: Sets the volume name, which must be unique within the containing pool (for disk pools, often derived from a device path plus partition index).
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] physical_unit: Sets the unit used for `physical` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] pool: Name of the storage pool where the volume will be created
        :param pulumi.Input[_builtins.str] type: Sets the actual storage volume type reported by libvirt (for example `file`, `block`, `dir`, `network`, `netdir`, or `ploop`), matching the `type` attribute libvirt exposes for the volume; the value is user-provided and should be consistent with the underlying storage backend.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-xml>
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VolumeArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Volume resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param VolumeArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VolumeArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 backing_store: Optional[pulumi.Input[Union['VolumeBackingStoreArgs', 'VolumeBackingStoreArgsDict']]] = None,
                 capacity: Optional[pulumi.Input[_builtins.float]] = None,
                 capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 create: Optional[pulumi.Input[Union['VolumeCreateArgs', 'VolumeCreateArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 physical_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 pool: Optional[pulumi.Input[_builtins.str]] = None,
                 target: Optional[pulumi.Input[Union['VolumeTargetArgs', 'VolumeTargetArgsDict']]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VolumeArgs.__new__(VolumeArgs)

            __props__.__dict__["allocation_unit"] = allocation_unit
            __props__.__dict__["backing_store"] = backing_store
            __props__.__dict__["capacity"] = capacity
            __props__.__dict__["capacity_unit"] = capacity_unit
            __props__.__dict__["create"] = create
            __props__.__dict__["name"] = name
            __props__.__dict__["physical_unit"] = physical_unit
            if pool is None and not opts.urn:
                raise TypeError("Missing required property 'pool'")
            __props__.__dict__["pool"] = pool
            __props__.__dict__["target"] = target
            __props__.__dict__["type"] = type
            __props__.__dict__["allocation"] = None
            __props__.__dict__["key"] = None
            __props__.__dict__["path"] = None
            __props__.__dict__["physical"] = None
        super(Volume, __self__).__init__(
            'libvirt:index/volume:Volume',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allocation: Optional[pulumi.Input[_builtins.float]] = None,
            allocation_unit: Optional[pulumi.Input[_builtins.str]] = None,
            backing_store: Optional[pulumi.Input[Union['VolumeBackingStoreArgs', 'VolumeBackingStoreArgsDict']]] = None,
            capacity: Optional[pulumi.Input[_builtins.float]] = None,
            capacity_unit: Optional[pulumi.Input[_builtins.str]] = None,
            create: Optional[pulumi.Input[Union['VolumeCreateArgs', 'VolumeCreateArgsDict']]] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            path: Optional[pulumi.Input[_builtins.str]] = None,
            physical: Optional[pulumi.Input[_builtins.float]] = None,
            physical_unit: Optional[pulumi.Input[_builtins.str]] = None,
            pool: Optional[pulumi.Input[_builtins.str]] = None,
            target: Optional[pulumi.Input[Union['VolumeTargetArgs', 'VolumeTargetArgsDict']]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None) -> 'Volume':
        """
        Get an existing Volume resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] allocation: Reports the currently allocated space for the volume (in the unit specified by allocation_unit), which may be less than the volume capacity for sparse formats.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] allocation_unit: Sets the unit for the allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if omitted, libvirt uses its default unit semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[Union['VolumeBackingStoreArgs', 'VolumeBackingStoreArgsDict']] backing_store: Configures an optional backing store volume for copy-on-write images, enabling layered storage where this volume records changes on top of another image.
        :param pulumi.Input[_builtins.float] capacity: Volume capacity in bytes (required unless using create.content)
        :param pulumi.Input[_builtins.str] capacity_unit: Sets the unit used for `capacity` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[Union['VolumeCreateArgs', 'VolumeCreateArgsDict']] create: Volume creation options for initializing volume content from external sources
        :param pulumi.Input[_builtins.str] key: Exposes the libvirt-assigned unique key identifying this volume within the pool, typically derived from the host path or backend identifier.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] name: Sets the volume name, which must be unique within the containing pool (for disk pools, often derived from a device path plus partition index).
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] path: Volume path on the host filesystem (same as target.path)
        :param pulumi.Input[_builtins.float] physical: Reports the actual physical space currently used by the volume on the underlying storage, as computed by libvirt.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] physical_unit: Sets the unit used for `physical` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        :param pulumi.Input[_builtins.str] pool: Name of the storage pool where the volume will be created
        :param pulumi.Input[_builtins.str] type: Sets the actual storage volume type reported by libvirt (for example `file`, `block`, `dir`, `network`, `netdir`, or `ploop`), matching the `type` attribute libvirt exposes for the volume; the value is user-provided and should be consistent with the underlying storage backend.
               
               See: <https://libvirt.org/formatstorage.html#storage-volume-xml>
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _VolumeState.__new__(_VolumeState)

        __props__.__dict__["allocation"] = allocation
        __props__.__dict__["allocation_unit"] = allocation_unit
        __props__.__dict__["backing_store"] = backing_store
        __props__.__dict__["capacity"] = capacity
        __props__.__dict__["capacity_unit"] = capacity_unit
        __props__.__dict__["create"] = create
        __props__.__dict__["key"] = key
        __props__.__dict__["name"] = name
        __props__.__dict__["path"] = path
        __props__.__dict__["physical"] = physical
        __props__.__dict__["physical_unit"] = physical_unit
        __props__.__dict__["pool"] = pool
        __props__.__dict__["target"] = target
        __props__.__dict__["type"] = type
        return Volume(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def allocation(self) -> pulumi.Output[_builtins.float]:
        """
        Reports the currently allocated space for the volume (in the unit specified by allocation_unit), which may be less than the volume capacity for sparse formats.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "allocation")

    @_builtins.property
    @pulumi.getter(name="allocationUnit")
    def allocation_unit(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the unit for the allocation value (for example, "bytes", "KiB", "MiB", "GiB"); if omitted, libvirt uses its default unit semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "allocation_unit")

    @_builtins.property
    @pulumi.getter(name="backingStore")
    def backing_store(self) -> pulumi.Output[Optional['outputs.VolumeBackingStore']]:
        """
        Configures an optional backing store volume for copy-on-write images, enabling layered storage where this volume records changes on top of another image.
        """
        return pulumi.get(self, "backing_store")

    @_builtins.property
    @pulumi.getter
    def capacity(self) -> pulumi.Output[_builtins.float]:
        """
        Volume capacity in bytes (required unless using create.content)
        """
        return pulumi.get(self, "capacity")

    @_builtins.property
    @pulumi.getter(name="capacityUnit")
    def capacity_unit(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the unit used for `capacity` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "capacity_unit")

    @_builtins.property
    @pulumi.getter
    def create(self) -> pulumi.Output[Optional['outputs.VolumeCreate']]:
        """
        Volume creation options for initializing volume content from external sources
        """
        return pulumi.get(self, "create")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        Exposes the libvirt-assigned unique key identifying this volume within the pool, typically derived from the host path or backend identifier.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Sets the volume name, which must be unique within the containing pool (for disk pools, often derived from a device path plus partition index).

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Output[_builtins.str]:
        """
        Volume path on the host filesystem (same as target.path)
        """
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def physical(self) -> pulumi.Output[_builtins.float]:
        """
        Reports the actual physical space currently used by the volume on the underlying storage, as computed by libvirt.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "physical")

    @_builtins.property
    @pulumi.getter(name="physicalUnit")
    def physical_unit(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the unit used for `physical` (for example `bytes`, `KiB`, `MiB`, `GiB`), matching libvirt’s `unit` attribute semantics.

        See: <https://libvirt.org/formatstorage.html#storage-volume-general-metadata>
        """
        return pulumi.get(self, "physical_unit")

    @_builtins.property
    @pulumi.getter
    def pool(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the storage pool where the volume will be created
        """
        return pulumi.get(self, "pool")

    @_builtins.property
    @pulumi.getter
    def target(self) -> pulumi.Output[Optional['outputs.VolumeTarget']]:
        return pulumi.get(self, "target")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the actual storage volume type reported by libvirt (for example `file`, `block`, `dir`, `network`, `netdir`, or `ploop`), matching the `type` attribute libvirt exposes for the volume; the value is user-provided and should be consistent with the underlying storage backend.

        See: <https://libvirt.org/formatstorage.html#storage-volume-xml>
        """
        return pulumi.get(self, "type")

